apiVersion: v1
kind: Service
metadata:
  name: {{ include "mywebapp.fullname" . }}
spec:
  selector:
    app: {{ include "mywebapp.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80

