apiVersion: v1
entries:
  mywebapp:
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2025-07-10T00:17:26.82527167+04:00"
    description: A Helm chart for Kubernetes
    digest: 87a63c002562d525542c7315493842c8ff2d53e8e820dfdd1cce74f9ee4789c1
    name: mywebapp
    type: application
    urls:
    - https://ibrahim88ku.github.io/mywebapp/mywebapp-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-07-10T00:17:26.825136157+04:00"
    description: A Helm chart for Kubernetes
    digest: 1c7f0bb70aff612019b1e5d64e8b6ca158672bc450bf476711abb5a660c8a40c
    name: mywebapp
    type: application
    urls:
    - https://ibrahim88ku.github.io/mywebapp/mywebapp-0.1.4.tgz
    version: 0.1.4
generated: "2025-07-10T00:17:26.824880247+04:00"
